services:
  mongo:
    image: mongo:7
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  uv:
    build:
      context: .
      args:
        UID: ${UID:-1000}
        GID: ${GID:-1000}
    working_dir: /workspace
    volumes:
      - .:/workspace
      - venv:/workspace/.venv
      - ${DATASETS_PATH:-./datasets}:/workspace/datasets
    stdin_open: true
    tty: true
    command: bash
    depends_on:
      - mongo
    # Additionally, you can expose the FiftyOne app port if you want to access it from your host machine
    ports:
      - "5151:5151"
    environment:
      FIFTYONE_DATABASE_URI: mongodb://mongo:27017
    user: appuser

volumes:
  mongo_data:
  venv: