[project]
name = "sar-detection"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "albumentations>=2.0.8",
    "fiftyone>=1.17.0",
    "lightning>=2.6.5",
    "pillow>=12.2.0",
    "pycocotools>=2.0.11",
    "sahi>=0.11.36",
    "torch>=2.12.0",
    "ultralytics>=8.4.52",
    "wandb>=0.28.0",
]
